import streamlit as st
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
import plotly.graph_objects as go

# --- CONFIGURATION & PAGE SETUP ---
st.set_page_config(page_title="High-Probability Swing Scanner", layout="wide", page_icon="📈")
st.title("🎯 3-4 Month Horizon Swing Trading Scanner")
st.markdown("Filters for structural uptrends exhibiting fresh momentum expansion with volume validation.")

# --- TICKER LISTS ---
# Preset lists for major indices. Customize these lists with symbols matching your target exchange.
TICKER_PRESETS = {
    "NIFTY 50 (India) Sample": ["RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS", "BHARTIARTL.NS", "SBIN.NS", "LTIM.NS", "TATAMOTORS.NS", "ITC.NS"],
    "US Mega Caps": ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "NFLX", "AMD", "COST"]
}

# --- SIDEBAR CONTROL PANEL ---
st.sidebar.header("⚙️ Scanner Controls")
market_selection = st.sidebar.selectbox("Select Target Market Preset", list(TICKER_PRESETS.keys()))
default_tickers = ", ".join(TICKER_PRESETS[market_selection])

raw_ticker_input = st.sidebar.text_area(
    "Modify/Paste Ticker Symbols (Comma Separated)", 
    value=default_tickers, 
    height=150
)

st.sidebar.markdown("---")
st.sidebar.subheader("Technical Threshold Tuning")
rsi_lower = st.sidebar.slider("RSI Lower Limit", 40, 65, 55)
rsi_upper = st.sidebar.slider("RSI Upper Limit", 65, 85, 70)
vol_multiplier = st.sidebar.slider("Min Volume Multiplier (vs 20MA)", 1.0, 3.0, 1.2, step=0.1)

# --- ENGINE FUNCTIONS ---
@st.cache_data(ttl=3600)  # Cache data for 1 hour to prevent redundant API thrashing
def fetch_and_analyze(tickers_list, rsi_l, rsi_u, vol_mult):
    scanned_results = []
    end_date = datetime.now()
    # Pull 1 year of historical daily data to accurately compute a 200-day SMA
    start_date = end_date - timedelta(days=365)
    
    progress_bar = st.progress(0)
    total = len(tickers_list)
    
    for idx, ticker_str in enumerate(tickers_list):
        ticker = ticker_str.strip().upper()
        if not ticker:
            continue
        try:
            df = yf.download(ticker, start=start_date, end=end_date, progress=False)
            if df.empty or len(df) < 200:
                continue
                
            # Flatten multi-level columns if generated by yfinance bulk downloads
            if isinstance(df.columns, pd.MultiIndex):
                df.columns = df.columns.get_level_values(0)

            # Calculate Core Indicators
            close_series = df['Close']
            df['150_SMA'] = close_series.rolling(window=150).mean()
            df['200_SMA'] = close_series.rolling(window=200).mean()
            df['20_Vol_EMA'] = df['Volume'].rolling(window=20).mean()
            
            # 14-Day RSI Calculation
            delta = close_series.diff()
            gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
            loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
            rs = gain / (loss + 1e-9)
            df['RSI'] = 100 - (100 / (1 + rs))
            
            # Extract Latest Values
            latest = df.iloc[-1]
            prev_close = df['Close'].iloc[-2]
            current_price = latest['Close']
            
            # Evaluate Trading Strategy Rules
            is_uptrend = current_price > latest['150_SMA'] > latest['200_SMA']
            is_rsi_momentum = rsi_l <= latest['RSI'] <= rsi_u
            is_volume_valid = latest['Volume'] >= (latest['20_Vol_EMA'] * vol_mult)
            
            if is_uptrend and is_rsi_momentum and is_volume_valid:
                pct_change = ((current_price - prev_close) / prev_close) * 100
                scanned_results.append({
                    "Ticker": ticker,
                    "Price": round(current_price, 2),
                    "Daily Change %": round(pct_change, 2),
                    "RSI (14)": round(latest['RSI'], 2),
                    "150 SMA": round(latest['150_SMA'], 2),
                    "200 SMA": round(latest['200_SMA'], 2),
                    "Volume Multiplier": round(latest['Volume'] / latest['20_Vol_EMA'], 2)
                })
        except Exception as e:
            pass # Gracefully skip processing errors for invalid listings
            
        progress_bar.progress((idx + 1) / total)
        
    progress_bar.empty()
    return pd.DataFrame(scanned_results)

# --- EXECUTION PIPELINE ---
parsed_tickers = [t.strip() for t in raw_ticker_input.split(",") if t.strip()]

if st.button("🚀 Run Institutional Swing Scan", type="primary"):
    with st.spinner("Processing technical indicators and matrix conditions..."):
        results_df = fetch_and_analyze(parsed_tickers, rsi_lower, rsi_upper, vol_multiplier)
        
    if not results_df.empty:
        st.success(f"Found {len(results_df)} high-probability candidates matching the setups!")
        
        # Color coding optimization formatting
        st.dataframe(
            results_df.style.background_gradient(subset=["Daily Change %"], cmap="RdYlGn")
                            .format({"Price": "{:.2f}", "Daily Change %": "{:+.2f}%", "RSI (14)": "{:.1f}"}),
            use_container_width=True
        )
        
        # Selected Candidate Technical Visualization Deep-Dive
        st.markdown("---")
        st.subheader("🔍 Interactive Technical Visualizer")
        selected_stock = st.selectbox("Pick a candidate stock from the scan to review chart setup:", results_df["Ticker"].unique())
        
        if selected_stock:
            chart_df = yf.download(selected_stock, start=datetime.now()-timedelta(days=260), end=datetime.now(), progress=False)
            if isinstance(chart_df.columns, pd.MultiIndex):
                chart_df.columns = chart_df.columns.get_level_values(0)
                
            chart_df['150_SMA'] = chart_df['Close'].rolling(window=150).mean()
            chart_df['200_SMA'] = chart_df['Close'].rolling(window=200).mean()
            
            fig = go.Figure()
            fig.add_trace(go.Candlestick(x=chart_df.index, open=chart_df['Open'], high=chart_df['High'], low=chart_df['Low'], close=chart_df['Close'], name="Price Action"))
            fig.add_trace(go.Scatter(x=chart_df.index, y=chart_df['150_SMA'], line=dict(color='orange', width=1.5), name="150 SMA"))
            fig.add_trace(go.Scatter(x=chart_df.index, y=chart_df['200_SMA'], line=dict(color='red', width=2), name="200 SMA"))
            
            fig.update_layout(title=f"{selected_stock} Structural Setup Analysis", xaxis_rangeslider_visible=False, template="plotly_dark", height=500)
            st.plotly_chart(fig, use_container_width=True)
            
    else:
        st.warning("No instruments matched the specified filter matrix today. Broaden filters or expand your tracking list.")
          
